// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elwybxbkyrcbtwyotvtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsd3lieGJreXJjYnR3eW90dnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzQyMDEsImV4cCI6MjA2ODkxMDIwMX0.aA7ztfonc08uq3GRm1bulvNpmVUVCEqITPFuXMt42ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});